import type { Board } from '../../workspace/index.ts'
import { idea } from '../utils/idea.ts'
import { link } from '../utils/link.ts'
export const boards: Board[] = [
  {
    id: 'layers',
    name: 'Deployment blueprint',
    description:
      'One reusable game layer. Many independently configured servers.',
    nodes: [
      idea(
        'base',
        'Runtime image',
        'A pinned base image and its runtime dependencies.',
        'layer',
        0,
        170,
        ['R13'],
        'Identify images by immutable digest. A shared artifact still has to be fetched or cached on each host.',
      ),
      idea(
        'game',
        'Game layer',
        'Install the game once. Version the result.',
        'layer',
        290,
        170,
        ['R13'],
        'Build an immutable artifact with game binaries. Keep save files and instance secrets out of the image. Confirm game redistribution rights before publishing images.',
      ),
      idea(
        'template',
        'Server blueprint',
        'Startup, mounts, resources, and an environment schema.',
        'service',
        580,
        170,
        ['R01', 'R04', 'R11', 'R13'],
        'Example parameters: GAME_PORT, SERVER_NAME, MAX_PLAYERS. Reference secrets separately. Validate types, defaults, required values, and port allocations before launch.',
      ),
      idea(
        'eu',
        'Survival · EU',
        'GAME_PORT=25565 · MAX_PLAYERS=20',
        'instance',
        900,
        0,
        ['R13'],
        'Own writable world volume and credentials; share the image digest, not writable data.',
      ),
      idea(
        'creative',
        'Creative · EU',
        'GAME_PORT=25566 · MAX_PLAYERS=40',
        'instance',
        900,
        180,
        ['R13'],
      ),
      idea(
        'us',
        'Survival · US',
        'GAME_PORT=25565 · REGION=us-east',
        'instance',
        900,
        360,
        ['R13'],
        'Port uniqueness is scoped to the host/binding. Distinct hosts may use the same port.',
      ),
      idea(
        'logs',
        'Durable event history',
        'Build output, crashes, and deployment results survive closed tabs.',
        'database',
        580,
        460,
        ['R05', 'R12'],
      ),
    ],
    edges: [
      link('base', 'game', 'build'),
      link('game', 'template', 'reuse'),
      link('template', 'eu', 'configure'),
      link('template', 'creative', 'configure'),
      link('template', 'us', 'configure'),
      link('template', 'logs', 'record'),
    ],
  },
  {
    id: 'system',
    name: 'Platform architecture',
    description:
      'A proposed control plane shared by self-hosted and hosted editions.',
    nodes: [
      idea(
        'user',
        'Operators & teams',
        'Project-scoped roles and visible effective access.',
        'person',
        0,
        130,
        ['R02', 'R07', 'R09'],
      ),
      idea(
        'panel',
        'Pomegranate web app',
        'Projects, batches, activity, and approachable diagnostics.',
        'service',
        290,
        0,
        ['R01', 'R03', 'R05'],
      ),
      idea(
        'iac',
        'API & IaC client',
        'One documented contract for UI and automation.',
        'service',
        290,
        250,
        ['R10', 'R15'],
        'Provider choice is open. Model desired state, plan/diff, apply, drift, and idempotent retries.',
      ),
      idea(
        'control',
        'Control plane',
        'Authorize, validate, schedule, and reconcile.',
        'service',
        600,
        120,
        ['R07', 'R15'],
        'Enforce authorization server-side on every resource. Batch requests need per-item outcomes and retry safety.',
      ),
      idea(
        'agent',
        'Node agent',
        'Execute workloads and report structured events.',
        'service',
        920,
        0,
        ['R04', 'R05', 'R11'],
      ),
      idea(
        'state',
        'State & audit store',
        'Desired state, sessions, audit trail, and job history.',
        'database',
        920,
        260,
        ['R02', 'R12'],
      ),
      idea(
        'providers',
        'Database providers',
        'PostgreSQL first; provider interface for additional engines.',
        'database',
        600,
        400,
        ['R06'],
        'PostgreSQL first is a proposal. Decide which engines are required and how backup/restore capabilities differ.',
      ),
    ],
    edges: [
      link('user', 'panel', 'interact'),
      link('user', 'iac', 'automate'),
      link('panel', 'control', 'API'),
      link('iac', 'control', 'desired state'),
      link('control', 'agent', 'jobs'),
      link('control', 'state', 'persist'),
      link('control', 'providers', 'provision'),
    ],
  },
  {
    id: 'journey',
    name: 'First deployment',
    description:
      'The operator journey from an empty project to a fleet of game servers.',
    nodes: [
      idea(
        'project',
        'Create a project',
        'Choose a name, environment, and team.',
        'person',
        0,
        0,
        ['R03'],
      ),
      idea(
        'choose',
        'Choose a blueprint',
        'Reuse a game layer or create a versioned build.',
        'layer',
        290,
        0,
        ['R13'],
      ),
      idea(
        'configure',
        'Configure instances',
        'Set count, per-instance env, ports, and volumes.',
        'service',
        580,
        0,
        ['R01', 'R04', 'R11'],
      ),
      idea(
        'review',
        'Review the plan',
        'See changes, conflicts, permissions, and resource needs.',
        'note',
        580,
        250,
        ['R07', 'R15'],
      ),
      idea(
        'run',
        'Launch the batch',
        'Track every item. Retry only the failures.',
        'instance',
        290,
        250,
        ['R01', 'R12'],
      ),
      idea(
        'observe',
        'Observe & recover',
        'Inspect retained logs, incident context, and rollback options.',
        'database',
        0,
        250,
        ['R05', 'R12'],
      ),
    ],
    edges: [
      link('project', 'choose', 'select'),
      link('choose', 'configure', 'customize'),
      link('configure', 'review', 'validate'),
      link('review', 'run', 'apply'),
      link('run', 'observe', 'inspect'),
    ],
  },
  {
    id: 'structure',
    name: 'Product structure',
    description:
      'Proposed navigation and the responsibilities of each product area.',
    nodes: [
      idea(
        'workspace',
        'Workspace',
        'The team, its projects, and shared resources.',
        'service',
        0,
        150,
        ['R03', 'R14'],
      ),
      idea(
        'projects',
        'Projects & environments',
        'Services grouped by purpose, with saved views and batch actions.',
        'service',
        300,
        0,
        ['R01', 'R03'],
      ),
      idea(
        'library',
        'Blueprint library',
        'Versioned game builds and reusable server configurations.',
        'layer',
        300,
        220,
        ['R13'],
      ),
      idea(
        'team',
        'People & access',
        'Roles, sessions, effective permissions, and audit history.',
        'person',
        300,
        440,
        ['R02', 'R07', 'R09'],
      ),
      idea(
        'service',
        'Service detail',
        'Overview, console, files, networking, storage, and startup.',
        'instance',
        650,
        0,
        ['R04', 'R08', 'R11'],
      ),
      idea(
        'activity',
        'Activity & incidents',
        'Durable, correlated events with role-aware diagnostics.',
        'database',
        650,
        220,
        ['R05', 'R12'],
      ),
      idea(
        'settings',
        'Infrastructure & settings',
        'Nodes, registries, database providers, API access, and edition settings.',
        'service',
        650,
        440,
        ['R04', 'R06', 'R10', 'R14'],
      ),
    ],
    edges: [
      link('workspace', 'projects', 'organize'),
      link('workspace', 'library', 'reuse'),
      link('workspace', 'team', 'collaborate'),
      link('projects', 'service', 'manage'),
      link('projects', 'activity', 'observe'),
      link('team', 'settings', 'authorize'),
    ],
  },
]
