packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@modelcontextprotocol/core@2.3.1'
  - '@modelcontextprotocol/server@2.3.1'
  - '@modelcontextprotocol/client@2.3.1'
  - vagabond-ui@0.4.0
patchedDependencies:
  vagabond-ui@0.4.0: patches/vagabond-ui@0.4.0.patch
