import type { Board, Idea, Requirement, Workspace } from './workspace.ts'

const idea = (
  id: string,
  title: string,
  description: string,
  kind: Idea['data']['kind'],
  x: number,
  y: number,
  requirements: string[] = [],
  notes = '',
): Idea => ({
  id,
  type: 'idea',
  position: { x, y },
  data: { title, description, kind, status: 'Exploring', requirements, notes },
})
const link = (source: string, target: string, label: string) => ({
  id: `${source}-${target}`,
  source,
  target,
  label,
  type: 'smoothstep' as const,
})
const req = (
  id: string,
  title: string,
  description: string,
  category: Requirement['category'],
  acceptance: string,
  priority: Requirement['priority'] = 'Must have',
): Requirement => ({
  id,
  title,
  description,
  category,
  priority,
  status: 'Captured',
  acceptance,
})
const boards: Board[] = [
  {
    id: 'layers',
    name: 'Deployment blueprint',
    description:
      'One reusable game layer. Many independently configured servers.',
    nodes: [
      idea(
        'base',
        'Runtime image',
        'A pinned base image and its runtime dependencies.',
        'layer',
        0,
        170,
        ['R13'],
        'Identify images by immutable digest. A shared artifact still has to be fetched or cached on each host.',
      ),
      idea(
        'game',
        'Game layer',
        'Install the game once. Version the result.',
        'layer',
        290,
        170,
        ['R13'],
        'Build an immutable artifact with game binaries. Keep save files and instance secrets out of the image. Confirm game redistribution rights before publishing images.',
      ),
      idea(
        'template',
        'Server blueprint',
        'Startup, mounts, resources, and an environment schema.',
        'service',
        580,
        170,
        ['R01', 'R04', 'R11', 'R13'],
        'Example parameters: GAME_PORT, SERVER_NAME, MAX_PLAYERS. Reference secrets separately. Validate types, defaults, required values, and port allocations before launch.',
      ),
      idea(
        'eu',
        'Survival · EU',
        'GAME_PORT=25565 · MAX_PLAYERS=20',
        'instance',
        900,
        0,
        ['R13'],
        'Own writable world volume and credentials; share the image digest, not writable data.',
      ),
      idea(
        'creative',
        'Creative · EU',
        'GAME_PORT=25566 · MAX_PLAYERS=40',
        'instance',
        900,
        180,
        ['R13'],
      ),
      idea(
        'us',
        'Survival · US',
        'GAME_PORT=25565 · REGION=us-east',
        'instance',
        900,
        360,
        ['R13'],
        'Port uniqueness is scoped to the host/binding. Distinct hosts may use the same port.',
      ),
      idea(
        'logs',
        'Durable event history',
        'Build output, crashes, and deployment results survive closed tabs.',
        'database',
        580,
        460,
        ['R05', 'R12'],
      ),
    ],
    edges: [
      link('base', 'game', 'build'),
      link('game', 'template', 'reuse'),
      link('template', 'eu', 'configure'),
      link('template', 'creative', 'configure'),
      link('template', 'us', 'configure'),
      link('template', 'logs', 'record'),
    ],
  },
  {
    id: 'system',
    name: 'Platform architecture',
    description:
      'A proposed control plane shared by self-hosted and hosted editions.',
    nodes: [
      idea(
        'user',
        'Operators & teams',
        'Project-scoped roles and visible effective access.',
        'person',
        0,
        130,
        ['R02', 'R07', 'R09'],
      ),
      idea(
        'panel',
        'Pomegranate web app',
        'Projects, batches, activity, and approachable diagnostics.',
        'service',
        290,
        0,
        ['R01', 'R03', 'R05'],
      ),
      idea(
        'iac',
        'API & IaC client',
        'One documented contract for UI and automation.',
        'service',
        290,
        250,
        ['R10', 'R15'],
        'Provider choice is open. Model desired state, plan/diff, apply, drift, and idempotent retries.',
      ),
      idea(
        'control',
        'Control plane',
        'Authorize, validate, schedule, and reconcile.',
        'service',
        600,
        120,
        ['R07', 'R15'],
        'Enforce authorization server-side on every resource. Batch requests need per-item outcomes and retry safety.',
      ),
      idea(
        'agent',
        'Node agent',
        'Execute workloads and report structured events.',
        'service',
        920,
        0,
        ['R04', 'R05', 'R11'],
      ),
      idea(
        'state',
        'State & audit store',
        'Desired state, sessions, audit trail, and job history.',
        'database',
        920,
        260,
        ['R02', 'R12'],
      ),
      idea(
        'providers',
        'Database providers',
        'PostgreSQL first; provider interface for additional engines.',
        'database',
        600,
        400,
        ['R06'],
        'PostgreSQL first is a proposal. Decide which engines are required and how backup/restore capabilities differ.',
      ),
    ],
    edges: [
      link('user', 'panel', 'interact'),
      link('user', 'iac', 'automate'),
      link('panel', 'control', 'API'),
      link('iac', 'control', 'desired state'),
      link('control', 'agent', 'jobs'),
      link('control', 'state', 'persist'),
      link('control', 'providers', 'provision'),
    ],
  },
  {
    id: 'journey',
    name: 'First deployment',
    description:
      'The operator journey from an empty project to a fleet of game servers.',
    nodes: [
      idea(
        'project',
        'Create a project',
        'Choose a name, environment, and team.',
        'person',
        0,
        0,
        ['R03'],
      ),
      idea(
        'choose',
        'Choose a blueprint',
        'Reuse a game layer or create a versioned build.',
        'layer',
        290,
        0,
        ['R13'],
      ),
      idea(
        'configure',
        'Configure instances',
        'Set count, per-instance env, ports, and volumes.',
        'service',
        580,
        0,
        ['R01', 'R04', 'R11'],
      ),
      idea(
        'review',
        'Review the plan',
        'See changes, conflicts, permissions, and resource needs.',
        'note',
        580,
        250,
        ['R07', 'R15'],
      ),
      idea(
        'run',
        'Launch the batch',
        'Track every item. Retry only the failures.',
        'instance',
        290,
        250,
        ['R01', 'R12'],
      ),
      idea(
        'observe',
        'Observe & recover',
        'Inspect retained logs, incident context, and rollback options.',
        'database',
        0,
        250,
        ['R05', 'R12'],
      ),
    ],
    edges: [
      link('project', 'choose', 'select'),
      link('choose', 'configure', 'customize'),
      link('configure', 'review', 'validate'),
      link('review', 'run', 'apply'),
      link('run', 'observe', 'inspect'),
    ],
  },
  {
    id: 'structure',
    name: 'Product structure',
    description:
      'Proposed navigation and the responsibilities of each product area.',
    nodes: [
      idea(
        'workspace',
        'Workspace',
        'The team, its projects, and shared resources.',
        'service',
        0,
        150,
        ['R03', 'R14'],
      ),
      idea(
        'projects',
        'Projects & environments',
        'Services grouped by purpose, with saved views and batch actions.',
        'service',
        300,
        0,
        ['R01', 'R03'],
      ),
      idea(
        'library',
        'Blueprint library',
        'Versioned game builds and reusable server configurations.',
        'layer',
        300,
        220,
        ['R13'],
      ),
      idea(
        'team',
        'People & access',
        'Roles, sessions, effective permissions, and audit history.',
        'person',
        300,
        440,
        ['R02', 'R07', 'R09'],
      ),
      idea(
        'service',
        'Service detail',
        'Overview, console, files, networking, storage, and startup.',
        'instance',
        650,
        0,
        ['R04', 'R08', 'R11'],
      ),
      idea(
        'activity',
        'Activity & incidents',
        'Durable, correlated events with role-aware diagnostics.',
        'database',
        650,
        220,
        ['R05', 'R12'],
      ),
      idea(
        'settings',
        'Infrastructure & settings',
        'Nodes, registries, database providers, API access, and edition settings.',
        'service',
        650,
        440,
        ['R04', 'R06', 'R10', 'R14'],
      ),
    ],
    edges: [
      link('workspace', 'projects', 'organize'),
      link('workspace', 'library', 'reuse'),
      link('workspace', 'team', 'collaborate'),
      link('projects', 'service', 'manage'),
      link('projects', 'activity', 'observe'),
      link('team', 'settings', 'authorize'),
    ],
  },
]
export function createSeed(): Workspace {
  return structuredClone({
    schemaVersion: 1,
    boards,
    requirements: [
      req(
        'R01',
        'Batch operations with per-item results',
        'Create multiple containers from the same configuration and grant a user access to several services in one operation.',
        'Deployment',
        'Select multiple targets, review the action, receive per-item success/failure results, and retry failed items without duplicating successful ones.',
      ),
      req(
        'R02',
        'Session control & sign-in history',
        'See who signed in, when, and from where. Revoke sessions without manually editing Redis or the panel database.',
        'Access',
        'List active sessions and sign-in events; revoke one or all sessions. Define password-reset revocation behavior. Prefer individual identities over shared accounts.',
      ),
      req(
        'R03',
        'Projects, folders & saved views',
        'Make a large fleet navigable through meaningful groups, tags, search, sorting, and filters.',
        'Experience',
        'Users can find a service by project, environment, name, status, or tag, and save a useful view.',
      ),
      req(
        'R04',
        'Registry credentials & mounts in the UI',
        'Configure image registry access and allowed volume mounts through an authorized workflow, without hand-editing node configuration.',
        'Operations',
        'Store credentials as secret references, verify image access, validate allowed host paths, and show mount errors before launch.',
      ),
      req(
        'R05',
        'Useful, role-aware diagnostics',
        'Show administrators actionable errors and separate workload events from noisy SFTP authentication traffic.',
        'Operations',
        'Provide event IDs, severity/source filters, relevant context, and redacted diagnostics based on the viewer’s role.',
      ),
      req(
        'R06',
        'Pluggable database providers',
        'Support database engines beyond MySQL through a clear provider capability model.',
        'Operations',
        'Define create/delete/credential rotation and backup capabilities; choose initial engines explicitly.',
      ),
      req(
        'R07',
        'Granular administration permissions',
        'Replace all-or-nothing administration with scoped roles and resource permissions.',
        'Access',
        'Authorize actions at workspace/project/service scope. Show effective access and deny unauthorized API operations.',
      ),
      req(
        'R08',
        'A file manager that handles large folders',
        'Browse directories with thousands of files without silent truncation or requiring SFTP.',
        'Experience',
        'Paginate or virtualize large listings, display total/loaded counts, and support search without hiding entries.',
      ),
      req(
        'R09',
        'User-centric access inventory',
        'Inspect every service a user can access and why access was granted.',
        'Access',
        'An authorized operator can view effective access, its role/group source, and revoke it in a batch.',
      ),
      req(
        'R10',
        'Documented, versioned API',
        'Make automation a first-class way to operate Pomegranate.',
        'Deployment',
        'Publish an OpenAPI contract with authentication, permissions, examples, errors, pagination, and versioning policy.',
      ),
      req(
        'R11',
        'Editable startup configuration',
        'Allow authorized users to change a service’s startup command and validated environment parameters.',
        'Deployment',
        'Preview the effective command, validate inputs, record the change, and clearly explain when restart is required.',
      ),
      req(
        'R12',
        'Retained build, runtime & incident logs',
        'Install logs and crash history must exist even when no browser is connected.',
        'Operations',
        'Reopen a failed installation or crash later and see ordered events with timestamps. Define retention, storage limits, and redaction.',
      ),
      req(
        'R13',
        'Reusable game layers & instance parameters',
        'Build game binaries once, add a reusable server configuration, then launch many isolated instances using environment values such as GAME_PORT.',
        'Deployment',
        'Version immutable artifacts and blueprints; allocate host ports; isolate writable data; inject per-instance configuration and secret references.',
      ),
      req(
        'R14',
        'Self-hosted and SaaS editions',
        'Ship an open-source self-hosted platform and offer a managed SaaS experience with a coherent core model.',
        'Deployment',
        'Document edition boundaries, upgrade/backup paths, and tenant isolation. Decide license and hosted billing separately.',
      ),
      req(
        'R15',
        'Declarative infrastructure workflow',
        'Represent desired infrastructure as a portable declaration that can be reviewed before application.',
        'Deployment',
        'Design plan/diff/apply, state reconciliation, drift reporting, and idempotency. Choose Terraform/OpenTofu or another integration after evaluation.',
      ),
    ],
    notes:
      '# Pomegranate\n\nA comfy deployment platform: open-source and self-hostable, with a managed SaaS offering.\n\n## Product principles\n- Reuse the work, not the writable state.\n- Batch actions should feel safe and predictable.\n- An incident should leave a useful history, even when nobody is watching.\n- Permissions should explain both what you can do and why.\n\n## References\nPterodactyl Panel and the user’s reference to Yandex deployment tooling (Arcanum / Deploy). The exact Yandex product/reference needs clarification. Pterodactyl pain points are user-reported experience, not a verified current-version audit.\n\n## Open decisions\n- Which games and deployment target should the first end-to-end flow support?\n- Which database engines are essential on day one?\n- How should the SaaS control plane connect to customer-owned nodes?\n- What is the boundary between the open-source and hosted editions?\n- Which UI language should the product ship first?\n\n## First milestone\nOne versioned game blueprint, two isolated instances, validated ports, scoped access, and retained installation logs.\n',
    design: {
      accent: '#b34568',
      density: 'Comfortable',
      direction:
        'A calm operations workspace with a strong information hierarchy. Quiet surfaces, legible data, a restrained berry accent, and clear feedback. Expressive details should make the system easier to understand. Reference Juxtopposed’s deliberate use of color and component-level exploration without copying a particular redesign.',
    },
  })
}
