export { designElementSchema } from './config/designElementSchema.ts'
export { designPageSchema } from './config/designPageSchema.ts'
export type { DesignElement, DesignPage } from './types/index.ts'
export { makeDesignElement } from './utils/makeDesignElement.ts'
export { removeDesignElements } from './utils/removeDesignElements.ts'
export { duplicateDesignElements } from './utils/duplicateDesignElements.ts'
export { createDesignTemplate } from './utils/createDesignTemplate.ts'

export { designSchema } from './config/designSchema.ts'
export { isDesignContainer } from './utils/isDesignContainer.ts'
export { designAncestors } from './utils/designAncestors.ts'
export { designDescendants } from './utils/designDescendants.ts'
export { designPosition } from './utils/designPosition.ts'
export { groupDesignElements } from './utils/groupDesignElements.ts'
export { ungroupDesignElements } from './utils/ungroupDesignElements.ts'
export { reparentDesignElement } from './utils/reparentDesignElement.ts'
export { applyDesignChanges } from './utils/applyDesignChanges.ts'
export { normalizeDesignGroups } from './utils/normalizeDesignGroups.ts'
