export { edgeTypes } from '@/widgets/board/config/canvasBoardEdgeTypes.ts'
export { nodeTypes } from '@/widgets/board/config/canvasBoardNodeTypes.ts'
export { defaultWidth } from '@/widgets/board/config/defaultWidth.ts'
export { kindIcons } from '@/widgets/board/config/kindIcons.ts'
export { kindLabels } from '@/widgets/board/config/kindLabels.ts'
export { maxWidth } from '@/widgets/board/config/maxWidth.ts'
export { minWidth } from '@/widgets/board/config/minWidth.ts'
export { storageKey } from '@/widgets/board/config/storageKey.ts'
export { edgeTypes as wireframeBoardEdgeTypes } from '@/widgets/board/config/wireframeBoardEdgeTypes.ts'
export { empty } from '@/widgets/board/config/wireframeBoardEmpty.ts'
export { icons } from '@/widgets/board/config/wireframeBoardIcons.ts'
export { nodeTypes as wireframeBoardNodeTypes } from '@/widgets/board/config/wireframeBoardNodeTypes.ts'
