export { edgeTypes } from './canvasBoardEdgeTypes.ts'
export { nodeTypes } from './canvasBoardNodeTypes.ts'
export { defaultWidth } from './defaultWidth.ts'
export { kindIcons } from './kindIcons.ts'
export { kindLabels } from './kindLabels.ts'
export { maxWidth } from './maxWidth.ts'
export { minWidth } from './minWidth.ts'
export { storageKey } from './storageKey.ts'
export { edgeTypes as wireframeBoardEdgeTypes } from './wireframeBoardEdgeTypes.ts'
export { empty } from './wireframeBoardEmpty.ts'
export { icons } from './wireframeBoardIcons.ts'
export { nodeTypes as wireframeBoardNodeTypes } from './wireframeBoardNodeTypes.ts'
