export { AccountConnection } from '@/widgets/collaboration/ui/AccountConnection.tsx'
export { CollaborationBar } from '@/widgets/collaboration/ui/CollaborationBar.tsx'
export { CollaborationPopover } from './CollaborationPopover.tsx'
export { CollaboratorList } from './CollaboratorList.tsx'
export { FollowPerson } from './FollowPerson.tsx'
export { ProfileForm } from './ProfileForm.tsx'
export { TeamActivityList } from './TeamActivityList.tsx'
export { WorkspaceAccountMenu } from './WorkspaceAccountMenu.tsx'

export { PeopleInvites } from './PeopleInvites.tsx'
