import type { DesignEditorState } from '../types/designEditorState.ts'
export function createDesignEditorState(): DesignEditorState {
  return {
    panelPositions: { left: null, right: null },
    dockMode: 'split',
    dockActive: 'left',
    dockPreview: null,
    layerActionsId: null,
    compact: false,
    panelSpace: 1000,
    panelVerticalSpace: 800,
    layersHeight: 520,
    inspectorHeight: 600,
    layersDockHeight: 280,
    inspectorDockHeight: 280,
    layersWidth: 280,
    inspectorWidth: 300,
    layersDocked: null,
    inspectorDocked: null,
    pageId: 'design-main',
    selection: [],
    drafts: {},
    tool: 'select',
    pagesOpen: false,
    pageQuery: '',
    layers: false,
    inspector: false,
    styles: false,
    editingId: null,
    collapsed: [],
    renamingPageId: null,
    renameDraft: '',
    contextPoint: null,
  }
}
